### ISSUE TITLE
[Bug] Genote request error stops the program

### ISSUE THREAD

**Issue by Snowius** [XavierFortin/Genote-Watcher-Go#1]
[2024/11/02 03:22:33] Aucun changement détecté
[2024/11/02 03:23:33] Aucun changement détecté
2024/11/02 03:24:52 Post "https://cas.usherbrooke.ca/login?service=https://www.usherbrooke.ca/genote/public/index.php": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Got this error around 24h ago and the docker container has been offline since then. I had to manually restart it since it was not showing up in "docker ps" so I'd assume the program crashed

In ScrapeCourseRows I think if there's an error on the request we should log it and return without completing the task? Assuming the crash happens there.

**Comment by XavierFortin** [comment]
I've checked my container and it seems to have worked in about the same time frame as yours. I think the site was down for a moment and since my TIME_INTERVAL is 3h I might have skipped past it. I will change the log so that it's not a "fatal" error and just log it as if it was a normal log to prevent the crash.
